version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/app
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/app:/app
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/app:/app
    ports:
      - 8080:80

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db: